<?php
/**
 * Created by PhpStorm.
 * User: Hiệp Nguyễn
 * Date: 21/10/2021
 * Time: 20:13
 */


namespace Nguyenhiep\LogShorter\Libs;


class Logger extends \Illuminate\Log\Logger
{
    protected function writeLog($level, $message, $context)
    {
        foreach (config("log-shorter.replacements") as $needed => $replace) {
            $message = str_replace($needed, $replace, $message);
            foreach ($context as &$item) {
                $item = str_replace($needed, $replace, $item);
            }
        }
        parent::writeLog($level, $message, $context); // TODO: Change the autogenerated stub
    }

}
