<?php
/**
 * Created by PhpStorm.
 * User: Hiệp Nguyễn
 * Date: 21/10/2021
 * Time: 20:13
 */


namespace Nguyenhiep\LogShorter\Libs;


class Logger extends \Illuminate\Log\Logger
{
    protected function writeLog($level, $message, $context)
    {
        foreach (config("log-shorter.replacements") as $needed => $replace) {
            $message = str_replace($needed, $replace, $message);
        }
        $this->replaceContext($context);
        parent::writeLog($level, $message, $context); // TODO: Change the autogenerated stub
    }

    private function replaceContext(&$context)
    {
        foreach (config("log-shorter.replacements") as $needed => $replace) {
            foreach ($context as &$item) {
                if (is_string($item)) {
                    $item = str_replace($needed, $replace, $item);
                } else if (is_countable($item)) {
                    $this->replaceContext($item);
                }
                // TODO: replace exception context
            }
        }
    }

}
